Repository apache/brpc, pull requests merged in 2023-06, with the labels that each got.

#2247 Log function name
  src/butil/logging.cc
  src/butil/logging.h
  test/logging_unittest.cc
Labels: enhancement

#2270 Support hint size of formatted string for string_printf
  src/butil/string_printf.cpp
  src/butil/string_printf.h
  test/string_printf_unittest.cpp
Labels: enhancement

#2180 Fix core when ssl is enabled
  src/brpc/socket.cpp
  src/brpc/socket.h
Labels: bug

#2210 Feature: Server-end progressive reader for http protocol
  src/brpc/controller.h
  src/brpc/details/http_message.h
  src/brpc/policy/http_rpc_protocol.cpp
  src/brpc/policy/http_rpc_protocol.h
  src/brpc/server.cpp
  src/brpc/server.h
  test/brpc_http_rpc_protocol_unittest.cpp
  test/echo.proto
Labels: feature

#2225 New DoublyBufferedData for suspended bthread
  src/butil/containers/doubly_buffered_data.h
  test/brpc_load_balancer_unittest.cpp
Labels: feature

#2231 Force SSL for all connections of Acceptor
  src/brpc/acceptor.cpp
  src/brpc/acceptor.h
  src/brpc/server.cpp
  src/brpc/server.h
  src/brpc/socket.cpp
  src/brpc/socket.h
  src/brpc/socket_inl.h
  test/brpc_channel_unittest.cpp
  test/brpc_input_messenger_unittest.cpp
  test/brpc_socket_unittest.cpp
  test/brpc_ssl_unittest.cpp
Labels: feature
